### ISSUE TITLE
Can't zoom in timeline unless video is playing

### ISSUE THREAD

**Issue by foralltimes** [dfaker/WebmGenerator#45]
Title is pretty much the issue. It's a little annoying to have to keep the video playing when I'm just trying to clarify an interest point or subclip starting point.

**Comment by foralltimes** [comment]
Also, not sure if anything could be done about overlapping subclips start/end points. Something to aid in accuracy of clip starts and ends.

**Comment by dfaker** [comment]
Canvas update callback added to zoom and pan events on timeline,

**Comment by dfaker** [comment]
I'm not sure there's a good general fix for the overlap issue, when they're perfectly abutted like in a 'cut into n equal sections' slice they are both available, and the handles are on the 'outside' of the relevant range they belong to:

![image](https://user-images.githubusercontent.com/35278260/140173548-1cd15725-e71c-455f-bd29-ea90593bae79.png)

, otherwise zooming will separate them (Ctrl and mouse wheel to zoom extra fast).

**Comment by dfaker** [comment]
Do we think something like this styling is clearer?

![image](https://user-images.githubusercontent.com/35278260/140177264-7e366aec-eb4f-445a-9060-c02a10c9c3cb.png)

**Comment by foralltimes** [comment]
I think either is fine. Do you think that the thickness and width of the handles are of note? In other programs, to avoid these sorts of things, content is usually just a block, so that the ends can meet flush. Perhaps having the handles be within the ends of the clip could clarify this? 

I was also thinking if you were committed to the block handles, a two-step process? I.e, you'd have to click on the handle/clip first to enable a stretching mode that when you click off, it'll prevent you from moving it again.

**Comment by dfaker** [comment]
> Perhaps having the handles be within the ends of the clip could clarify this?
🤦🏿 perfect.

**Comment by dfaker** [comment]
In other programs, to avoid these sorts of things, content is usually just a block, so that the ends can meet flush. Perhaps having the handles be within the ends of the clip could clarify this?

What "Sorts of things" are we thinking of here, Are you finding it hard to select the Correct endpoint when there's an overlap? Dragging the portion of the handle 'above' the level of the green lines may help with this.

I'm not sure what usability advantage having the handles on the inside rather than the outside brings, it also brings the trade-off that short clips will have their own start and end handles overlapping. Can you describe a situation where you're having trouble?

**Comment by foralltimes** [comment]
> Are you finding it hard to select the correct endpoint when there's an overlap? 
That's pretty much it, when I want two separate clips where one ends at the start of the other. A specific example could also be when you have a long scene that you want several clips of, but you can also stitch them together in the merge tab and export as one clip. 

> Dragging the portion of the handle 'above' the level of the green lines may help with this.
Not quite sure what you mean, sorry.

**Comment by dfaker** [comment]
If you want perfectly sequential clips you have two options without messing around with the dragging:

Pause the video, go to the start position, press v use the arrow keys to go to the end position, and then in the command menu select one of the splitting options, it should prompt you if you want to use the selected range.

Or

Add a subclip as normal covering the whole length of the total clip you want, seek to the position you want the cut in the middle of the subclip to be at, press c to add a cut.

**Comment by foralltimes** [comment]
Ah, good to know. I also had another stray suggestion. When you have a lot of subclips where there is a scrollbar on the merge page, when you press 'add to sequence' on a clip towards the end, it resets the scrollbar to the first position. Any way to prevent it from resetting?

**Comment by dfaker** [comment]
Okay skipback on add and remove disabled, it was a workaround for an issue with the scroll bars freezing in earlier releases, but we'll see how it goes, worst case switching tabs performs the same reset.
